name: Common Setup Action
description: Sets up Node.js environment and installs dependencies

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci --include dev
