name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: '22'
  NPM_CACHE: 'npm'

jobs:
  install-and-compile:
    name: Install Dependencies and Compile Smart Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NPM_CACHE }}

      - name: Install Dependencies
        run: npm ci --include dev

      - name: Compile Smart Contracts
        run: npm run compile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compilation-artifacts
          path: |
            artifacts
            cache
            typechain-types
          include-hidden-files: true
          if-no-files-found: error

  test:
    name: Test Smart Contracts
    runs-on: ubuntu-latest
    needs: install-and-compile
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NPM_CACHE }}

      - name: Install Dependencies
        run: npm ci --include dev

      - name: Compile Smart Contracts
        run: npm run compile

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compilation-artifacts

      - name: Run Coverage with Unit Tests
        run: npm run coverage

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            coverage
            coverage.json
          include-hidden-files: true
          if-no-files-found: error

  analyze:
    name: Analyze Codebase
    runs-on: ubuntu-latest
    needs: install-and-compile
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.NPM_CACHE }}

      - name: Install Dependencies
        run: npm ci --include dev

      - name: Compile Smart Contracts
        run: npm run compile

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compilation-artifacts

      - name: Run ESLint
        run: npm run eslint-check

      - name: Run Prettier
        run: npm run prettier-check

      - name: Run Solhint
        run: npm run solhint

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          slither-args: --exclude-dependencies --filter-paths openzeppelin
